import { StyleSheet, Dimensions, Platform } from 'react-native';
import type { Theme } from '@/contexts/ThemeContext';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export function createStyles(theme: Theme) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollView: {
      flex: 1,
      zIndex: 1,
      backgroundColor: theme.background,
    },
    scrollContent: {
      paddingTop: 260,
      paddingBottom: 140,
      backgroundColor: theme.background,
    },
    fixedHeaderBackground: {
      position: 'absolute' as const,
      top: 0,
      left: 0,
      right: 0,
      height: 260,
      zIndex: 10,
      overflow: 'hidden' as const,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
    },
    headerImage: {
      width: '100%',
      height: '100%',
      backgroundColor: theme.surface,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
    },
    headerGradient: {
      position: 'absolute' as const,
      top: 0,
      left: 0,
      right: 0,
      height: 120,
    },
    headerNav: {
      position: 'absolute' as const,
      top: 0,
      left: 0,
      right: 0,
      flexDirection: 'row' as const,
      justifyContent: 'space-between' as const,
      paddingHorizontal: 24,
      zIndex: 1000,
    },
    navButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.surface + 'D9',
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      ...Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 8 },
        android: { elevation: 8 },
      }),
    },
    headerNavRight: { flexDirection: 'row' as const, gap: 12 },
    categoryBadgeContainer: {
      position: 'absolute' as const,
      bottom: 24,
      right: 20,
    },
    categoryBadge: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      backgroundColor: theme.surface + 'D9',
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      gap: 8,
      ...Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 8 },
        android: { elevation: 8 },
      }),
    },
    categoryIcon: { fontSize: 20 },
    categoryText: { fontSize: 14, fontWeight: '900' as const, color: theme.textPrimary },
    contentContainer: {
      backgroundColor: theme.surface,
      borderTopLeftRadius: 40,
      borderTopRightRadius: 40,
      marginTop: -32,
      minHeight: SCREEN_HEIGHT,
      paddingBottom: 40,
      borderTopWidth: 1,
      borderTopColor: theme.border,
      ...Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: -8 }, shadowOpacity: 0.4, shadowRadius: 20 },
        android: { elevation: 20 },
      }),
    },
    questionHeader: {
      paddingHorizontal: 24,
      paddingTop: 48,
      paddingBottom: 8,
    },
    questionTitleRow: {
      flexDirection: 'row' as const,
      alignItems: 'flex-start' as const,
      justifyContent: 'space-between' as const,
      marginBottom: 8,
    },
    questionTitle: {
      flex: 1,
      fontSize: 24,
      fontWeight: '900' as const,
      color: theme.textPrimary,
      lineHeight: 32,
      paddingRight: 16,
    },
    rightColumn: { alignItems: 'flex-end' as const, gap: 6 },
    ratingBadge: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      backgroundColor: theme.surfaceCard,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      gap: 4,
      borderWidth: 1,
      borderColor: theme.border,
    },
    ratingText: { fontSize: 14, fontWeight: '900' as const, color: theme.textPrimary },
    metaRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
      marginBottom: 12,
    },
    metaItem: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8 },
    metaText: { fontSize: 14, fontWeight: '700' as const, color: theme.textMuted },
    voteCountBadge: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      backgroundColor: theme.surfaceCard,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      gap: 6,
      borderWidth: 1,
      borderColor: theme.border,
    },
    voteCountText: { fontSize: 14, fontWeight: '900' as const, color: theme.textPrimary },
    voteCountLabel: { fontSize: 12, fontWeight: '700' as const, color: theme.textMuted },
    countdownBadge: {
      backgroundColor: theme.surfaceCard + 'CC',
      borderRadius: 10,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderWidth: 1,
      borderColor: theme.border + '99',
      ...Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 4 },
        android: { elevation: 2 },
      }),
    },
    countdownBadgeValue: { fontSize: 18, fontWeight: '800' as const, color: theme.textPrimary, textAlign: 'center' as const, marginBottom: 1 },
    countdownBadgeLabel: { fontSize: 9, fontWeight: '700' as const, color: theme.textMuted, textAlign: 'center' as const, letterSpacing: 0.5 },
    tabs: { flexDirection: 'row' as const, gap: 4, marginBottom: 4, paddingHorizontal: 4 },
    tab: {
      flex: 1,
      paddingTop: 6,
      paddingBottom: 12,
      paddingHorizontal: 4,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      position: 'relative' as const,
    },
    tabActive: { backgroundColor: theme.accent + '1A' },
    tabContent: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, gap: 6 },
    tabText: { fontSize: 12, fontWeight: '900' as const, color: theme.textMuted },
    tabTextActive: { color: theme.accent },
    commentCountBadge: {
      backgroundColor: theme.surfaceCard,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 12,
    },
    commentCountBadgeActive: { backgroundColor: theme.accent },
    commentCountText: { fontSize: 12, fontWeight: '700' as const, color: theme.textMuted },
    commentCountTextActive: { color: theme.textInverse },
    tabIndicator: {
      position: 'absolute' as const,
      bottom: 0,
      left: 0,
      right: 0,
      height: 4,
      backgroundColor: theme.accent,
      borderRadius: 2,
    },
    divider: { height: 1, marginBottom: 0 },
    detailsTabContainer: { flex: 1, flexDirection: 'column' as const, paddingHorizontal: 24, paddingTop: 0 },
    descriptionSection: { marginBottom: 20 },
    descriptionText: { fontSize: 16, lineHeight: 24, color: theme.textSecondary, marginBottom: 12 },
    // Vote bar
    compactVoteBar: {
      position: 'absolute' as const,
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: theme.surface,
      borderTopWidth: 1,
      borderTopColor: theme.border,
      zIndex: 1000,
      ...Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.3, shadowRadius: 12 },
        android: { elevation: 12 },
      }),
    },
    compactVoteRow: {
      flexDirection: 'row' as const,
      flexWrap: 'nowrap' as const,
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
      paddingHorizontal: 18,
      paddingVertical: 4,
      minHeight: 68,
    },
    compactVoteBtn: {
      flex: 1,
      maxWidth: 160,
      flexDirection: 'column' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      paddingVertical: 8,
      paddingHorizontal: 8,
      borderRadius: 12,
      borderWidth: 2,
      gap: 4,
      overflow: 'hidden' as const,
      ...Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 6 },
        android: { elevation: 4 },
      }),
    },
    compactVoteBtnYes: {
      backgroundColor: theme.accent + '1F',
      borderColor: theme.accent + '80',
    },
    compactVoteBtnNo: {
      backgroundColor: theme.error + '1F',
      borderColor: theme.error + '80',
    },
    compactVoteBtnPressed: { transform: [{ scale: 0.98 }] },
    compactVoteDivider: {
      width: 1,
      height: 34,
      backgroundColor: theme.border,
      marginHorizontal: 62,
      borderRadius: 1,
      alignSelf: 'center' as const,
    },
    compactVoteLabelYes: { fontSize: 18, fontWeight: '800' as const, color: theme.accent, letterSpacing: 0.5, lineHeight: 22 },
    compactVoteLabelNo: { fontSize: 18, fontWeight: '800' as const, color: theme.error, letterSpacing: 0.5, lineHeight: 22 },
    compactVoteOdds: { fontSize: 14, fontWeight: '700' as const, color: theme.textMuted, marginTop: 0 },
    userPredictionBadge: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 12,
      backgroundColor: theme.surfaceCard,
      borderWidth: 1,
      borderColor: theme.border,
    },
    userPredictionText: { fontSize: 14, fontWeight: '700' as const, color: theme.textSecondary },
    loadingContainer: { flex: 1, justifyContent: 'center' as const, alignItems: 'center' as const },
    errorText: { fontSize: 16, fontWeight: '600' as const, color: theme.error, textAlign: 'center' as const, paddingHorizontal: 32 },
  });
}

export { SCREEN_WIDTH, SCREEN_HEIGHT };
