-- Zip Puzzles Table for Daily Puzzle System
-- This table stores generated puzzles that can be assigned to specific dates

CREATE TABLE IF NOT EXISTS zip_puzzles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  daily_date DATE UNIQUE NOT NULL,
  size INTEGER NOT NULL DEFAULT 6,
  total_numbers INTEGER NOT NULL,
  cells JSONB NOT NULL,
  difficulty TEXT DEFAULT 'medium' CHECK (difficulty IN ('easy', 'medium', 'hard')),
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'live')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  approved_by UUID REFERENCES profiles(id)
);

-- Index for quick date lookup
CREATE INDEX IF NOT EXISTS idx_zip_puzzles_daily_date ON zip_puzzles(daily_date);
CREATE INDEX IF NOT EXISTS idx_zip_puzzles_status ON zip_puzzles(status);

-- RLS Policies
ALTER TABLE zip_puzzles ENABLE ROW LEVEL SECURITY;

-- Anyone can read approved/live puzzles
CREATE POLICY "Anyone can read live puzzles" ON zip_puzzles
  FOR SELECT USING (status = 'live');

-- Admins can do everything
CREATE POLICY "Admins can manage puzzles" ON zip_puzzles
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.is_admin = true
    )
  );

COMMENT ON TABLE zip_puzzles IS 'Stores daily Zip game puzzles generated by admin';
COMMENT ON COLUMN zip_puzzles.daily_date IS 'The date when this puzzle should be shown';
COMMENT ON COLUMN zip_puzzles.cells IS 'JSON array of cell definitions for the puzzle grid';
COMMENT ON COLUMN zip_puzzles.status IS 'draft: not ready, approved: ready but not live, live: shown to users';
